language: node_js
node_js:
  - "4"
  - "5"
  - "6"
sudo: false
before_install:
  - npm i -g npm@latest
  - cd test && npm install && cd ../
before_script:
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
