language: node_js
node_js:
  - "4"
  - "5"
  - "6"
sudo: false
before_install:
  - npm install --global npm@latest
  - npm install --global lerna@2.0.0-beta.28
  - lerna bootstrap
  - cd test && npm install && cd ../
before_script:
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
addons:
  firefox: "49.0"
